language: node_js

node_js:
  - '5'

cache:
  directories:
    - node_modules

install:
  - npm install

before_script:
  - npm run build

script:
  - npm test

after_success:
  - bash <(curl -s https://codecov.io/bash)
